version: '3'
services:
  jenkins:
    image: "jenkins/jenkins:2.121.3-alpine"
    container_name: jenkins-server
    volumes:
      - ${WORKSPACE}jenkins-home:/var/jenkins_home
    ports:
      - 8080:8080 # jenkins port
      - 50000:50000 # image requirement
      - 5005:5005 # jenkins debug port
      - 5015:5015 # BuildInfo debug port
    environment:
      - 'JPDA_OPTS=-agentlib:jdwp=transport=dt_socket, address=5005, server=y, suspend=n'

  jenkins-agent:
    # See https://support.cloudbees.com/hc/en-us/articles/115001771692-How-to-Create-Permanent-Agents-with-Docker#jnlpconnection
    image: "jenkins/jnlp-slave"
    container_name: jenkins-agent
    volumes:
      - ${WORKSPACE}jenkins-agent:/var/jenkins_agent
    ports:
      - 5006:5005 # jenkins agent debug port
      - 5016:5015 # BuildInfo debug port
    environment:
      - 'JENKINS_URL=http://jenkins:8080'
      - 'JENKINS_SECRET=${JENKINS_SECRET}'
      - 'JENKINS_AGENT_NAME=agent1'
      - 'JENKINS_AGENT_WORKDIR=/var/jenkins_agent'
      - 'JPDA_OPTS=-agentlib:jdwp=transport=dt_socket, address=5005, server=y, suspend=n'
    restart: on-failure
    depends_on:
      - jenkins

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:6.5.1
    container_name: art8082
    ports:
      - 8082:8081
    volumes:
      - ${ART_WORKSPACE}8082:/var/opt/jfrog/artifactory
    restart: on-failure