version: '3'
services:
  teamcity:
    image: "jetbrains/teamcity-server:2018.1.2"
    container_name: teamcity-server
    volumes:
    - ${MAIN_WORKSPACE}server:/data/teamcity_server/datadir
    - ${MAIN_WORKSPACE}logs/server:/opt/teamcity/logs
    ports:
    - 8111:8111
    - 5007:5005 # teamcity debug port
    - 5017:5015 # BuildInfo debug port
    environment:
    - 'TEAMCITY_SERVER_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005'

  teamcity-agent:
    image: "jetbrains/teamcity-agent:2018.1.2"
    container_name: teamcity-agent
    volumes:
    - ${MAIN_WORKSPACE}agent/conf:/data/teamcity_agent/conf
    - ${MAIN_WORKSPACE}logs/agent:/opt/buildagent/logs
    ports:
    - 5008:5005 # teamcity agent debug port
    - 5018:5015 # BuildInfo debug port
    environment:
    - 'SERVER_URL=http://teamcity:8111'
    - 'TEAMCITY_AGENT_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005'
    depends_on:
    - teamcity

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:6.5.1
    container_name: art8083
    ports:
    - 8083:8081
    volumes:
    - ${ART_WORKSPACE}8083:/var/opt/jfrog/artifactory
    restart: on-failure